app = 'balatro-challenge-hub-dev'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = 'https://wzibnlshgoknzrnkfebi.supabase.co'
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_n9C-klXBt4c4zRIWFm6kaA_YN4tfvpE'

[env]
  PORT = '3000'
  HOSTNAME = '0.0.0.0'

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
